name: Test composite action

on: [push]

jobs:
  local-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Run local action
        uses: ./.github/actions/my-actions
